name = "cf-test-trigger"
main = "src/workers/db-trigger.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding (same as main app)
[[d1_databases]]
binding = "DB"
database_name = "cf-test-db"
database_id = "your-database-id-here"  # Will be replaced after creating D1 database

# Scheduled triggers (cron jobs)
[[triggers]]
crons = ["0 2 * * *"]  # Run daily at 2 AM UTC

# Routes for manual triggers
[[routes]]
pattern = "your-domain.com/trigger/*"
zone_name = "your-domain.com"

[env.production]
name = "cf-test-trigger-production"

[env.staging]
name = "cf-test-trigger-staging"
