name = "cf-test"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = [
  # Enable Node.js API
  "nodejs_compat",
  # Allow to fetch URLs in your app
  "global_fetch_strictly_public",
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
# The service should match the "name" of your worker
service = "cf-test"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "cf-test-db"
database_id = "your-database-id-here"  # Will be replaced after creating D1 database

# R2 bucket for Next.js caching (optional)
# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "cf-test-cache"

# Environment variables for production
[env.production]
name = "cf-test-production"

[env.production.vars]
NEXTJS_ENV = "production"
NODE_ENV = "production"

# Environment variables for staging
[env.staging]
name = "cf-test-staging"

[env.staging.vars]
NEXTJS_ENV = "staging"
NODE_ENV = "production"
