name = "cf-test"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = [
  # Enable Node.js API
  "nodejs_compat",
  # Allow to fetch URLs in your app
  "global_fetch_strictly_public",
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
# The service should match the "name" of your worker
service = "cf-test"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "cf-test-db"
database_id = "aa730d18-dac4-4fc8-b39d-cdf8e13913e2"
migrations_dir = "drizzle"

# R2 bucket for Next.js caching (optional)
# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "cf-test-cache"
